### ISSUE TITLE
Ensure original author is still the author post-land

### ISSUE THREAD

**Issue by 3-n** [repo-mono/phlq#34]
"Open question: If the service lands a diff, will the author be the bot account that lands it? Or the user that submitted the diff? We want the diff authorship to be the original author.
The comitter will be the original author. The pusher will be the bot account. Unclear how to squash signed commits, we’ll have to investigate this."

**Comment by alexeagle** [comment]
For the robinhood deployment of the service, we'll make a github app with a token that we auth with, and that github app will appear as the user that does the push. From the demo this morning we saw the original author was preserved so that's good.
Maybe should leave this open to identify problems with signed commits though.

**Comment by bart84ek** [comment]
I found issue on local env (Git author and username is not injected during build and i got "" author).
I'll make sure the author is set up correctly locally and during deployment.

**Comment by bart84ek** [comment]
I decided to create a separate task to investigate sigining #54 .
