### ISSUE TITLE
Update external/README

### ISSUE THREAD

**Issue by karolmartyna** [repo-mono/phlq#39]
I've got a problem with installation process of phlq client.
```
running install
error: can't create or remove files in install directory
...

    [Errno 13] Permission denied: '/Library/Python/2.7/site-p.......
```
to omit error it needs to use `python3`.

**Comment by szewczykmira** [comment]
What other problems do you encounter? Are there any additional steps you had to do that are missing from Readme?
As for:
> to omit error it needs to use python3

There is information about required software at the beginning of readme which informs you that you need python3


Also, there are different steps how can you achieve using python in version 3 and some of them allow you to run `python3` as `python`. I'm not sure this is the place to inform users how to obtain that especially that this differ on different systems.

**Comment by szewczykmira** [comment]
Srsly I should stop thinking about work right after woking up... 😂
- The `permission denied` can be solved by using `python setup.py install --user` or you could also install it using `sudo` 👹
Either way - none of this matters, because this script is not backwards compatible
- In the main [Readme](https://github.com/repo-mono/phlq#installation) there is info about using virtualenv to obtain a proper version of python __but__ there is a need to install dependencies there. And dependencies do need their separate environment. 


There are some solutions I can think of here:
1. Change command to `python3 setup.py install`
2. Provide information about virtualenv. This can be tricky for people who don't work with python on a daily basis, because they would need to make sure that they will enable it before landing revisions.
3. Both at the same time.

Please let me know if there are any other issues you had to solve. Maybe they came from missing steps in the installation.
