### ISSUE TITLE
Export basic stats for monitoring

### ISSUE THREAD

**Issue by alexeagle** [repo-mono/phlq#66]
https://statsd.readthedocs.io/en/v3.3/ is probably the library to use. It can expose a few variables that we'll use to monitor/alert on problems with the service. Off the top of my head I'd guess most useful are:
- merge requests per second
- responses per second by response code (most interesting being errors/sec)
- since the service is async we also need the result of each request
- latency (how long the last request took to merge)

**Comment by bart84ek** [comment]
So i added bunch of counters and one timer to cover whole process.

- land requests, counter: `landing.request`
- land response, counters: `landing.response.success` or `landing.response.failure`. This endpoints adds revision number to queue, so there is not much here to fail.

async task for landing
- timer: `landing`
- counters `landing.success` or `landing.failure`

Since landing is async we don't have info how long full process takes `land request` -> `waiting in queue` -> `actual landing`.
